import { Upload, FileText } from "lucide-react";
import Navbar from "./Navbar";

interface Transaction {
  id: string;
  amount: string;
  status: "fraud" | "genuine";
}

interface ResultsScreenProps {
  onNavigate: (screen: string) => void;
  transactions?: Transaction[];
}

export default function ResultsScreen({ onNavigate, transactions = [] }: ResultsScreenProps) {
  const totalTransactions = transactions.length;
  const fraudulentTransactions = transactions.filter(r => r.status === "fraud").length;

  return (
    <div className="min-h-screen bg-black">
      {/* Top Navbar */}
      <Navbar onNavigate={onNavigate} currentScreen="results" />

      {/* Main Content Area */}
      <main className="p-6 md:p-12 pt-24 pb-24 md:pb-12">
        <div className="max-w-6xl mx-auto">
          {/* Page Title */}
          <h1 className="text-4xl font-bold text-white mb-3">
            Fraud Detection Results
          </h1>
          <p className="text-lg text-gray-400 mb-8">
            Classification results generated by the fraud detection model
          </p>

          {transactions.length > 0 ? (
            <>
              {/* Summary Cards */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
                <div className="bg-[#111111] border border-gray-800 rounded-lg p-6">
                  <p className="text-gray-400 text-sm mb-2">Total Transactions Analyzed</p>
                  <p className="text-4xl font-bold text-white">{totalTransactions}</p>
                </div>
                <div className="bg-[#111111] border border-gray-800 rounded-lg p-6">
                  <p className="text-gray-400 text-sm mb-2">Fraudulent Transactions Detected</p>
                  <p className="text-4xl font-bold text-red-500">{fraudulentTransactions}</p>
                </div>
              </div>

              {/* Results Table */}
              <div className="bg-[#111111] border border-gray-800 rounded-lg overflow-hidden">
                <div className="overflow-x-auto">
                  <table className="w-full">
                    <thead>
                      <tr className="border-b border-gray-800">
                        <th className="text-left px-6 py-4 text-gray-400 font-semibold text-sm">
                          Transaction ID
                        </th>
                        <th className="text-left px-6 py-4 text-gray-400 font-semibold text-sm">
                          Amount
                        </th>
                        <th className="text-left px-6 py-4 text-gray-400 font-semibold text-sm">
                          Prediction Status
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      {transactions.map((result, index) => (
                        <tr 
                          key={result.id}
                          className={`border-b border-gray-800 hover:bg-gray-900 transition-colors ${
                            index === transactions.length - 1 ? 'border-b-0' : ''
                          }`}
                        >
                          <td className="px-6 py-4 text-white font-mono">
                            {result.id}
                          </td>
                          <td className="px-6 py-4 text-white">
                            {result.amount}
                          </td>
                          <td className="px-6 py-4">
                            {result.status === "fraud" ? (
                              <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-semibold bg-red-600 text-white">
                                Fraud
                              </span>
                            ) : (
                              <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-semibold bg-green-600 text-white">
                                Genuine
                              </span>
                            )}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </>
          ) : (
            <div className="bg-[#111111] border border-gray-800 rounded-lg p-12 text-center">
              <p className="text-gray-400 text-lg mb-4">No transaction data available</p>
              <button
                onClick={() => onNavigate('upload')}
                className="bg-red-600 text-white px-6 py-3 rounded-lg font-medium hover:bg-red-700 transition-colors"
              >
                Upload Transactions
              </button>
            </div>
          )}
        </div>
      </main>

      {/* Bottom Navigation Bar for Mobile */}
      <nav className="md:hidden fixed bottom-0 left-0 right-0 bg-[#111111] border-t border-gray-800 z-50">
        <div className="flex justify-around items-center h-16">
          <button
            onClick={() => onNavigate('upload')}
            className="flex flex-col items-center justify-center flex-1 h-full text-gray-400"
          >
            <Upload className="w-6 h-6 mb-1" />
            <span className="text-xs">Upload</span>
          </button>
          <button
            onClick={() => onNavigate('results')}
            className="flex flex-col items-center justify-center flex-1 h-full text-red-600"
          >
            <FileText className="w-6 h-6 mb-1" />
            <span className="text-xs">Results</span>
          </button>
        </div>
      </nav>
    </div>
  );
}
